# Generated by Django 5.2.4 on 2025-07-23 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('timeframe', models.CharField(choices=[('day', 'Daily'), ('week', 'Weekly'), ('month', 'Monthly')], max_length=10)),
                ('start_price', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('end_price', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('change_pct', models.FloatField()),
                ('change_abs', models.DecimalField(decimal_places=10, max_digits=20)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest.stock')),
            ],
        ),
        migrations.CreateModel(
            name='SentimentChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('timeframe', models.CharField(choices=[('day', 'Daily'), ('week', 'Weekly'), ('month', 'Monthly')], max_length=10)),
                ('start_score', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('end_score', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('change_pct', models.FloatField()),
                ('change_abs', models.DecimalField(decimal_places=3, max_digits=5)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest.stock')),
            ],
        ),
    ]
