# Generated by Django 5.2.4 on 2025-08-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0003_alter_prediction_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='text',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
