# Generated by Django 5.2.4 on 2025-08-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0004_text_description_text_title_alter_text_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentiment',
            name='num_texts',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
