# Generated by Django 5.2.4 on 2025-08-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0005_sentiment_num_texts'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='sentiment_label',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
