# Generated by Django 5.2.4 on 2025-08-09 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0006_text_sentiment_label'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='text',
            unique_together={('stock', 'url')},
        ),
    ]
